### ISSUE TITLE
SCIM bridge public IP address no longer displayed after marketplace deployment

### ISSUE THREAD

**Issue by devillexio** [1Password/op-scim-gcp-marketplace#54]
After moving to the Helm chart the marketplace application no longer shows the SCIM bridge public IP address.

The symptoms are:
1. the application state remains in "Some components are pending", and
2. the "1Password SCIM bridge public IP" is not populated under the "SCIM bridge info" section and the following message is displayed instead: "Referenced object not found" (see screenshot below)

<img width="356" alt="SCIM bridge info - Referenced object not found" src="https://user-images.githubusercontent.com/11049609/182665150-e4b1b03f-a83f-43f8-942b-f25faa1dc134.png">

The SCIM bridge deployment still succeeds, but the public IP address is not shown as expected. It can still be obtained from the deployed SCIM bridge load balancer service, but this does not align with our support documentation on how to deploy the SCIM bridge.

**Comment by devillexio** [comment]
I'm reop

**Comment by devillexio** [comment]
I'm reopening this issue as it seems it wasn't fixed with the changes in https://github.com/1Password/op-scim-gcp-marketplace/pull/55.

**Comment by devillexio** [comment]
This remains an issue if you use the default name of `op-scim-bridge-X`, where `X` is a number (usually "1").

The reference is correctly set when you use an app instance name that does not contain "op-scim-bridge". The reason the reference breaks is that we use bitnami/common to construct the full name and that drops the duplication of "op-scim-bridge" in the name if the release also contains "op-scim-bridge". It's intended to shorten the name and reduce stutter, but for now it also breaks the setting of `serviceRef`.

**Comment by alicethorne-ab** [comment]
This appears to have been fixed, in my latest testing on GCP. Marking as resolved unless it comes up again.
