### ISSUE TITLE
How does one make use of static IPs in GCP with this application?

### ISSUE THREAD

**Issue by jessesanford** [1Password/op-scim-gcp-marketplace#64]
Examples are needed, the op-scim-helm chart has a template for ingress and we could make use of that, but it looks like you reference the service when surfacing the public IP to users. Can you give an example of how ingress can be used to specify a static ip address?

**Comment by jessesanford** [comment]
I imagine you will need to use the following annotation on the ingress: `kubernetes.io/ingress.global-static-ip-name` from https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer

**Comment by alicethorne-ab** [comment]
Apologies for the late response on this issue.

If you're looking to configure a static *ingress* IP, we do have documentation for that located [here](https://support.1password.com/scim-deploy-gcp/#23-configure-a-static-ip-address) as part of our GCP onboarding procedures.

If you're looking to configure a static *egress* IP, while we have worked out an (unsupported) solution to do so, we typically do not recommend customers implement it, as it is typically more trouble than it is worth, and requires a certain level of expertise in GCP to manage appropriately.

I hope this answers your questions. Please let me know if there's anything else we can help you with.
